theme: jekyll-theme-minimal
title: Sparkling with SPARQL
description: A collection of SPARQL-Queries on French Englightenment novels
image: 
![Voltaire](https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Voltaire_-_%C3%89l%C3%A9mens_de_la_philosophie_de_Neuton.png/324px-Voltaire_-_%C3%89l%C3%A9mens_de_la_philosophie_de_Neuton.png)
